os: osx
osx_image: xcode9.2
language: objective-c
before_script: 
  - swiftlint
  - pod lib lint
script:
  - swift build
  - swift test
  - xcodebuild test -project Puree.xcodeproj -scheme PureeTests -destination 'platform=iOS Simulator,name=iPhone 8'
