os: osx
osx_image: xcode9.2
language: objective-c
before_script: 
  - swiftlint
  - pod lib lint
matrix:
  include:
    - env: NAME=SPM
    - env: NAME=Xcode
script:
  - if [ $NAME = "Xcode" ]; then xcodebuild test -project Puree.xcodeproj -scheme PureeTests -destination 'platform=iOS Simulator,name=iPhone 8'; else swift test; fi
