name: Puree
on: [push, pull_request]
jobs:
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests with Xcode
      run: |
        DESTINATION="platform=iOS Simulator,name=iPhone 8" SCHEME="Puree"
        xcodebuild test -project Puree.xcodeproj -scheme "${SCHEME}" -destination "${DESTINATION}" -configuration Debug CODE_SIGNING_ALLOWED=NO
  SwiftPM:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests with Swift Package Manager
      run: swift test
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
  CocoaPodsLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        gem install cocoapods
        pod repo update
    - name: CocoaPods
      run: pod lib lint --allow-warnings
